language: node_js
node_js:
  - "8.9.0"
before_install:
  - npm i -g npm@5.6.0
cache:
  directories:
  - $HOME/.npm
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app: transparency-sing
  on:
    branch: master
